# Generated by Django 3.2.8 on 2021-12-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsKota_web', '0003_auto_20211204_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_to',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
